### ISSUE TITLE
Option to run a package without `-it`

### ISSUE THREAD

**Issue by hdp617** [whalebrew/whalebrew#134]
I think the `-it` option in `docker run` is only needed to provide interactive input. When running a command and piping the output e.g. to a tool like`jq`,  interactive input is not needed [0].

I propose adding an option to run a package without `-it`. For example, we can add a runtime env var like `WHALEBREW_USETTY`, default to true and we can run a package without interactive input with `WHALEBREW_USETTY=false <command>`

[0] https://stackoverflow.com/q/65824304

**Comment by tjamet** [comment]
good point! thanks for raising
I believe though this should be detectable from std in/outs
Currently, we [use stdin](https://github.com/whalebrew/whalebrew/blob/784d26c33cae0cc6843c65f296a8cab2cf56a126/cmd/run.go#L134) to trigger the `--tty`  argument

This is indeed maybe not enough. Do you have some examples of packages and commands that are suffering the problem?

**Comment by hdp617** [comment]
Thanks for the pointer. I _think_ the same thing can be done for --interactive as well i.e don't set this flag if stdout is not piped to the terminal. Unclear how robust this is.

**Comment by tjamet** [comment]
> I think the same thing can be done for --interactive as well

I am quite unsure. `--interactive` is about binding stdin, this allows to pipe whalebrew commands.

![image](https://user-images.githubusercontent.com/6061440/118867341-433b9f80-b8e3-11eb-8742-faf0fb4aec6e.png)

> All interactive commands whose output is piped to a file or other tools will suffer the problem

I actually run most of my clis in whalebrew and have both jq and aws cli pointed in the above post containerized, and didn't have the mentioned problem as illustrated in the snapshot below

![image](https://user-images.githubusercontent.com/6061440/118867147-0bccf300-b8e3-11eb-8784-472a4a1d7311.png)

After some more investigation, I think the fix would be to only open a TTY when both stdin and stdout are TTYs. 
This fixes the problem mentioned, but still prevents from being to run the last item in the pipe chain as a whalebrew program.
Say we have `less` as a whalebrew package, we cannot run `aws logs describe-log-groups | less` and have the expected behavior.

This is not a regression towards the current behavior. I think it is safe to proceed with such a change, and  see how to support the above pattern later on
